### ISSUE TITLE
Forwarded (reverse) ports

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-vagrant#62]
Allow custom forwarded ports to be configured. This will allow the box to talk to other service running on the host machines (jekyll sites, node.js apps, ..)

Example from a Puphpet config:

```
 vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: mybox
        memory: '512'
        cpus: '1'
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_8n82k04lyz3d:
                    host: '6178'
                    guest: '22'
                vflnp_n319oy1hyfdg:
                    host: '3306'
                    guest: '33060'
[...]
```
